# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "CAPBS 2018 Meeting, Nijmegen"
email: "openscience.weekend@gmail.com"
description: "Chinese Association for Psychological & Brain Sciences 2018 Meeting"
baseurl: "/eurobrainmeeting2018"
url: "https://nijmegenow.github.io"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-26255736-2"
googleAnalyticsSiteUrl: "nijmegenow.github.io"
siteVerification: ""
googleMapsJSAPI: "AIzaSyAyLtVe_9lSWGPXFhdkLIBWu8V9eZAiF9E"

# Organizer Info
organizerName: "CAPBS NL"
organizerAlternateName: "Chinese Association for Psychological & Brain Sciences"
organizerDescription: "Open communities who share experience about psychological & brain sciences with passions."
organizerEmail: "openscience.weekend@gmail.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "https://nijmegenow.github.io/eurobrainmeeting2018/"

# Head
metaKeywords: "brain, psychology, psychological, association, society, Chinese, Nijmegen, MPI, Donders, Europe, European"
twitterAccount: "@CAPBS"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://goo.gl/2Xgruc"
c4sponsorsUrl: "/assets/CABPS_Info_v1.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "News"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/team/", text: "Team"}
 - {permalink: "/logistics/", text: "Logistics"}
bottomNavigationLinks:
 - {link: "https://goo.gl/2Xgruc", text: "Become a speaker"}
rightNavigationButtons:
 - {link: "https://goo.gl/2Xgruc", text: "Become a speaker"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "Chinese Association for Psychological & Brain Sciences <typeout> 2018 Meeting"
heroTitleCN: "欧洲华人心理与脑科学会议"
heroTitleCN2: "暨 第二届52brain欧洲学术沙龙"
eventRegion: "Europe"
eventCity: "Nijmegen, Netherlands"
eventDate: "October 20-21, 2018"
typeoutTextValues: '"", "Nijmegen, Netherlands", "Amsterdam, Netherlands", "Beijing, China","Berlin, Germany","Bielefeld, Germany","Bonn, Germany","Frankfurt, Germany","Ghent, Belgium","Groningen, Netherlands","Jönköping, Sweden","Jülich, Germany","Leiden, Netherlands","Maastricht, Netherlands","Nijmengen, Netherlands","Tilburg, Netherlands","Utrecht, Netherlands"'
typeoutFallback: "Nijmegen, Netherlands"
heroButtons:
 - {link: "https://goo.gl/2Xgruc", text: "Become a speaker"}
 - {link: "https://goo.gl/jpELhK", text: "&nbsp;&nbsp;&nbsp;Registration&nbsp;&nbsp;&nbsp"}

# About Block
aboutTitle: "The CAPBS 2018 Meeting"
aboutBlock:
 - {title: "青年/Youth", image: "youth.png", text: "By Youth For Youth. We have awseome speakers, fantastic audience, and lots of fun!" }
 - {title: "开放/Open", image: "open.png", text: "An Open community. We would like to share our experience and expertise, and learn from Peers." }
 - {title: "连接/Network", image: "network.png", text: "Good way to seek for Collaboration possibilities. Come and join our two-day party!" }
 - {title: "科学/Science", image: "science.jpg", text: "Everyone has a passion for Psychological & Brain Sciences. Follow your passions and sharpen your brain!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "50", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "48", specialCharacter: "+", info: "hours", detail: "of pure brain sciences"}
 - {count: "15", specialCharacter: "+", info: "speakers", detail: "from Europe and beyond"}
 - {count: "6", specialCharacter: "", info: "topics", detail: "plus free discussion"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Red room of Donders Centre for Cognitive Neuroimaging"
eventLocationLink: "https://nijmegenow.github.io/eurobrainmeeting2018/"
eventStreetAddress: "Kapittelweg 29"
eventAddressLocality: "Nijmegen"
eventAddressLocalityRegion: "Nijmegen"
eventPostalCode: "6525"
eventAddressCountry: "Netherlands"
eventStartTime: "2018-10-21T09:20"
eventDoorTime: "09:00"
eventEndTime: "2018-10-21T16:00"
eventPlaceCoordinates: "51.826243, 5.863146"
mapCenterCoordinates: "51.826243, 5.863146"
mapMobileCenterCoordinates: "51.826243, 5.863146"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Kinopalace Cinema"
venueFeatures: ["3 huge cinema screens", "Doulby Digital Surround EX audio system", "Located directly in the city center"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "CAPBS2018"
twitterFeed: "http://#"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://#"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Registration"
ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Early Bird"
  price: "350"
  priceCurrency: "UAH"
  ticketsNumber: "150"
  ribbon: "-5%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-25T10:00"
  validThrough: "2014-09-30T23:59"
 -
  name: "Last Chance"
  price: "450"
  priceCurrency: "UAH"
  ticketsNumber: "100"
  ribbon: "-20%"
  featured: true
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-10-01T00:00"
  validThrough: "2014-10-23T23:59"
  disabled: true
 -
  name: "Student"
  price: "200"
  priceCurrency: "UAH"
  ticketsNumber: "50"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-20T10:00"
  validThrough: "2014-10-23T23:59"
  soldOut: true
  soldOutText: "Sold Out"

# Footer
socialLinks:
 - {link: "https://twitter.com/intent/user?screen_name=CAPBS2", icon: "twitter"}
 - {link: "https://weibo.com/52brain", icon: "weibo"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://nijmegenow.github.io/eurobrainmeeting2018/", text: "CAPBS 2018"}
   - {link: "http://www.52brain.com/", text: "我爱脑科学52brain"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:openscience.weekend@gmail.com", text: "openscience.weekend@gmail.com"}
 -
  title: "FAQ"
  links:
   - {link: "https://twitter.com/intent/user?screen_name=CAPBS2", text: "Frequently Asked Questions"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "CAPBS"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "关于我们/About us"
aboutUs: "华人心理与脑科学学会是由海内外华人心理与脑科学学者组成的公益性、学术性社会团体，宗旨是汇集海内外广大心理与脑科学学者，开展学术活动，交流互通，促进合作，以更好地开展心理与脑科学研究，促进华人心理与脑科学人才的成长和提高。"

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "49.056728, 3.117289"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Nijmegen"
directionDetailsCards:
 - {title: "From the Airport", information: 'The closet airports are the international airport Schiphol Amsterdam, Dusseldorf Airport, and Eindhoven Airport. It is easily reachable by car, public transport or taxi from these airports to Nijmegen.'}
 - {title: "Public Transit", information: 'Google Maps App works very well in the Netherlands. So you can find your way in this App.'}
 - {title: "Hotels", information: 'Nijmegen has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {permalink: "/cod/", text: "FAQ"}
   -
    title: "Registration"
    links:
     - {permalink: "/cod/", text: "FAQ"}
   -
    title: "Attendance Details"
    links:
     - {permalink: "/cod/", text: "FAQ"}

